### ISSUE TITLE
Fix for Trinket slots?

### ISSUE THREAD

**Issue by Sheggs2** [JosiahFu/GravestonesFix#1]
Heya, first of all great fix, I lost everything i had to water destroying the grave and been annoyed with the gravestones mod since.

Something else I noticed when that happened is that things i had equipped via trinket slots were dropped normally instead of going into the gravestone leaving them vulnerable to despawning or burning.

I dont know much about modding but I assume this is because the gravestones ask for specific inventory slots instead of the whole inventory which is why stuff in trinket slots didn't get saved.

**Comment by ThePotatoArchivist** [comment]
That's true, people on my server have experienced this too. I didn't think of fixing this initially, but that's a good idea and probably within scope of the mod. I'll take a look.

**Comment by ThePotatoArchivist** [comment]
That's funny, the original gravestones mod has a class called `TrinketsCompat` but I guess it doesn't work?

**Comment by Pouri-Shoon** [comment]
OMG guys plz fix we have the same issue

**Comment by ThePotatoArchivist** [comment]
Alright sorry it's been a really long time. If this is still an issue, what version of Trinkets are you using?

**Comment by ThePotatoArchivist** [comment]
Can you try version [1.1.0](https://modrinth.com/mod/gravestones-fix/version/1.1.0) and let me know if it's still an issue?

**Comment by Sheggs2** [comment]
I was using Trinkets version 3.7.1 for Fabric 1.20.1. I will try the same setup with 1.1.0 and get back to you.

**Comment by ThePotatoArchivist** [comment]
Thanks! FYI I tested against trinkets 3.7.2, so could you try that if 3.7.1 doesn't work?

**Comment by Sheggs2** [comment]
I tried tests with all slots filled and with only trinket slots fill and it looks like everything works fine, both with 3.7.2 and 3.7.1. Thanks for the fix, this means 1.20.1 fab is back on the menu for me and another friend!
